server:
  port: 10000

spring:
  application:
    name: erp-single
  profiles:
    active: @env@
  mvc:
    servlet:
      load-on-startup: 1
    problemdetails:
      enabled: on
    pathmatch:
      matching-strategy: ant_path_matcher
  threads:
    virtual:
      enabled: on
  aop:
    auto: on
    proxy-target-class: on
  datasource:
    driver-class-name: org.postgresql.Driver

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:}){magenta} - %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID} - [%t] %-40.40logger{39} : %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"